# Generated by Django 5.2.1 on 2026-07-15 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0003_alter_product_collection_review'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='desciption',
            new_name='description',
        ),
    ]
