# Generated by Django 5.2.1 on 2026-07-17 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_alter_customer_options_remove_customer_email_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'permissions': [('cancel_order', 'Can cancel order')]},
        ),
    ]
