# Generated by Django 5.2.1 on 2026-07-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0009_alter_orders_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'ordering': ['user__first_name', 'user__last_name'], 'permissions': [('view_history', 'Can View History.')]},
        ),
    ]
