# Generated by Django 5.2.1 on 2026-07-03 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tags', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taggeditem',
            old_name='contentType',
            new_name='content_type',
        ),
    ]
